/*
 FontAwesomeCpp
 
 Copyright (c) 2015, Simon Geilfus - All rights reserved.
 
 Redistribution and use in source and binary forms, with or without modification, are permitted provided that
 the following conditions are met:
 
 * Redistributions of source code must retain the above copyright notice, this list of conditions and
 the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and
 the following disclaimer in the documentation and/or other materials provided with the distribution.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.
*/
#pragma once

#include <string>

#ifndef FONTAWESOME_NO_TYPEDEF
    typedef class FontAwesome fa;
#endif

class FontAwesome {
public:
	static std::string glass() { return "\uf000"; }
	static std::string music() { return "\uf001"; }
	static std::string search() { return "\uf002"; }
	static std::string envelope_o() { return "\uf003"; }
	static std::string heart() { return "\uf004"; }
	static std::string star() { return "\uf005"; }
	static std::string star_o() { return "\uf006"; }
	static std::string user() { return "\uf007"; }
	static std::string film() { return "\uf008"; }
	static std::string th_large() { return "\uf009"; }
	static std::string th() { return "\uf00a"; }
	static std::string th_list() { return "\uf00b"; }
	static std::string check() { return "\uf00c"; }
	static std::string remove() { return "\uf00d"; }
	static std::string close() { return "\uf00d"; }
	static std::string times() { return "\uf00d"; }
	static std::string search_plus() { return "\uf00e"; }
	static std::string search_minus() { return "\uf010"; }
	static std::string power_off() { return "\uf011"; }
	static std::string signal() { return "\uf012"; }
	static std::string gear() { return "\uf013"; }
	static std::string cog() { return "\uf013"; }
	static std::string trash_o() { return "\uf014"; }
	static std::string home() { return "\uf015"; }
	static std::string file_o() { return "\uf016"; }
	static std::string clock_o() { return "\uf017"; }
	static std::string road() { return "\uf018"; }
	static std::string download() { return "\uf019"; }
	static std::string arrow_circle_o_down() { return "\uf01a"; }
	static std::string arrow_circle_o_up() { return "\uf01b"; }
	static std::string inbox() { return "\uf01c"; }
	static std::string play_circle_o() { return "\uf01d"; }
	static std::string rotate_right() { return "\uf01e"; }
	static std::string repeat() { return "\uf01e"; }
	static std::string refresh() { return "\uf021"; }
	static std::string list_alt() { return "\uf022"; }
	static std::string lock() { return "\uf023"; }
	static std::string flag() { return "\uf024"; }
	static std::string headphones() { return "\uf025"; }
	static std::string volume_off() { return "\uf026"; }
	static std::string volume_down() { return "\uf027"; }
	static std::string volume_up() { return "\uf028"; }
	static std::string qrcode() { return "\uf029"; }
	static std::string barcode() { return "\uf02a"; }
	static std::string tag() { return "\uf02b"; }
	static std::string tags() { return "\uf02c"; }
	static std::string book() { return "\uf02d"; }
	static std::string bookmark() { return "\uf02e"; }
	static std::string print() { return "\uf02f"; }
	static std::string camera() { return "\uf030"; }
	static std::string font() { return "\uf031"; }
	static std::string bold() { return "\uf032"; }
	static std::string italic() { return "\uf033"; }
	static std::string text_height() { return "\uf034"; }
	static std::string text_width() { return "\uf035"; }
	static std::string align_left() { return "\uf036"; }
	static std::string align_center() { return "\uf037"; }
	static std::string align_right() { return "\uf038"; }
	static std::string align_justify() { return "\uf039"; }
	static std::string list() { return "\uf03a"; }
	static std::string dedent() { return "\uf03b"; }
	static std::string outdent() { return "\uf03b"; }
	static std::string indent() { return "\uf03c"; }
	static std::string video_camera() { return "\uf03d"; }
	static std::string photo() { return "\uf03e"; }
	static std::string image() { return "\uf03e"; }
	static std::string picture_o() { return "\uf03e"; }
	static std::string pencil() { return "\uf040"; }
	static std::string map_marker() { return "\uf041"; }
	static std::string adjust() { return "\uf042"; }
	static std::string tint() { return "\uf043"; }
	static std::string edit() { return "\uf044"; }
	static std::string pencil_square_o() { return "\uf044"; }
	static std::string share_square_o() { return "\uf045"; }
	static std::string check_square_o() { return "\uf046"; }
	static std::string arrows() { return "\uf047"; }
	static std::string step_backward() { return "\uf048"; }
	static std::string fast_backward() { return "\uf049"; }
	static std::string backward() { return "\uf04a"; }
	static std::string play() { return "\uf04b"; }
	static std::string pause() { return "\uf04c"; }
	static std::string stop() { return "\uf04d"; }
	static std::string forward() { return "\uf04e"; }
	static std::string fast_forward() { return "\uf050"; }
	static std::string step_forward() { return "\uf051"; }
	static std::string eject() { return "\uf052"; }
	static std::string chevron_left() { return "\uf053"; }
	static std::string chevron_right() { return "\uf054"; }
	static std::string plus_circle() { return "\uf055"; }
	static std::string minus_circle() { return "\uf056"; }
	static std::string times_circle() { return "\uf057"; }
	static std::string check_circle() { return "\uf058"; }
	static std::string question_circle() { return "\uf059"; }
	static std::string info_circle() { return "\uf05a"; }
	static std::string crosshairs() { return "\uf05b"; }
	static std::string times_circle_o() { return "\uf05c"; }
	static std::string check_circle_o() { return "\uf05d"; }
	static std::string ban() { return "\uf05e"; }
	static std::string arrow_left() { return "\uf060"; }
	static std::string arrow_right() { return "\uf061"; }
	static std::string arrow_up() { return "\uf062"; }
	static std::string arrow_down() { return "\uf063"; }
	static std::string mail_forward() { return "\uf064"; }
	static std::string share() { return "\uf064"; }
	static std::string expand() { return "\uf065"; }
	static std::string compress() { return "\uf066"; }
	static std::string plus() { return "\uf067"; }
	static std::string minus() { return "\uf068"; }
	static std::string asterisk() { return "\uf069"; }
	static std::string exclamation_circle() { return "\uf06a"; }
	static std::string gift() { return "\uf06b"; }
	static std::string leaf() { return "\uf06c"; }
	static std::string fire() { return "\uf06d"; }
	static std::string eye() { return "\uf06e"; }
	static std::string eye_slash() { return "\uf070"; }
	static std::string warning() { return "\uf071"; }
	static std::string exclamation_triangle() { return "\uf071"; }
	static std::string plane() { return "\uf072"; }
	static std::string calendar() { return "\uf073"; }
	static std::string random() { return "\uf074"; }
	static std::string comment() { return "\uf075"; }
	static std::string magnet() { return "\uf076"; }
	static std::string chevron_up() { return "\uf077"; }
	static std::string chevron_down() { return "\uf078"; }
	static std::string retweet() { return "\uf079"; }
	static std::string shopping_cart() { return "\uf07a"; }
	static std::string folder() { return "\uf07b"; }
	static std::string folder_open() { return "\uf07c"; }
	static std::string arrows_v() { return "\uf07d"; }
	static std::string arrows_h() { return "\uf07e"; }
	static std::string bar_chart_o() { return "\uf080"; }
	static std::string bar_chart() { return "\uf080"; }
	static std::string twitter_square() { return "\uf081"; }
	static std::string facebook_square() { return "\uf082"; }
	static std::string camera_retro() { return "\uf083"; }
	static std::string key() { return "\uf084"; }
	static std::string gears() { return "\uf085"; }
	static std::string cogs() { return "\uf085"; }
	static std::string comments() { return "\uf086"; }
	static std::string thumbs_o_up() { return "\uf087"; }
	static std::string thumbs_o_down() { return "\uf088"; }
	static std::string star_half() { return "\uf089"; }
	static std::string heart_o() { return "\uf08a"; }
	static std::string sign_out() { return "\uf08b"; }
	static std::string linkedin_square() { return "\uf08c"; }
	static std::string thumb_tack() { return "\uf08d"; }
	static std::string external_link() { return "\uf08e"; }
	static std::string sign_in() { return "\uf090"; }
	static std::string trophy() { return "\uf091"; }
	static std::string github_square() { return "\uf092"; }
	static std::string upload() { return "\uf093"; }
	static std::string lemon_o() { return "\uf094"; }
	static std::string phone() { return "\uf095"; }
	static std::string square_o() { return "\uf096"; }
	static std::string bookmark_o() { return "\uf097"; }
	static std::string phone_square() { return "\uf098"; }
	static std::string twitter() { return "\uf099"; }
	static std::string facebook() { return "\uf09a"; }
	static std::string github() { return "\uf09b"; }
	static std::string unlock() { return "\uf09c"; }
	static std::string credit_card() { return "\uf09d"; }
	static std::string rss() { return "\uf09e"; }
	static std::string hdd_o() { return "\uf0a0"; }
	static std::string bullhorn() { return "\uf0a1"; }
	static std::string bell() { return "\uf0f3"; }
	static std::string certificate() { return "\uf0a3"; }
	static std::string hand_o_right() { return "\uf0a4"; }
	static std::string hand_o_left() { return "\uf0a5"; }
	static std::string hand_o_up() { return "\uf0a6"; }
	static std::string hand_o_down() { return "\uf0a7"; }
	static std::string arrow_circle_left() { return "\uf0a8"; }
	static std::string arrow_circle_right() { return "\uf0a9"; }
	static std::string arrow_circle_up() { return "\uf0aa"; }
	static std::string arrow_circle_down() { return "\uf0ab"; }
	static std::string globe() { return "\uf0ac"; }
	static std::string wrench() { return "\uf0ad"; }
	static std::string tasks() { return "\uf0ae"; }
	static std::string filter() { return "\uf0b0"; }
	static std::string briefcase() { return "\uf0b1"; }
	static std::string arrows_alt() { return "\uf0b2"; }
	static std::string group() { return "\uf0c0"; }
	static std::string users() { return "\uf0c0"; }
	static std::string chain() { return "\uf0c1"; }
	static std::string link() { return "\uf0c1"; }
	static std::string cloud() { return "\uf0c2"; }
	static std::string flask() { return "\uf0c3"; }
	static std::string cut() { return "\uf0c4"; }
	static std::string scissors() { return "\uf0c4"; }
	static std::string copy() { return "\uf0c5"; }
	static std::string files_o() { return "\uf0c5"; }
	static std::string paperclip() { return "\uf0c6"; }
	static std::string save() { return "\uf0c7"; }
	static std::string floppy_o() { return "\uf0c7"; }
	static std::string square() { return "\uf0c8"; }
	static std::string navicon() { return "\uf0c9"; }
	static std::string reorder() { return "\uf0c9"; }
	static std::string bars() { return "\uf0c9"; }
	static std::string list_ul() { return "\uf0ca"; }
	static std::string list_ol() { return "\uf0cb"; }
	static std::string strikethrough() { return "\uf0cc"; }
	static std::string underline() { return "\uf0cd"; }
	static std::string table() { return "\uf0ce"; }
	static std::string magic() { return "\uf0d0"; }
	static std::string truck() { return "\uf0d1"; }
	static std::string pinterest() { return "\uf0d2"; }
	static std::string pinterest_square() { return "\uf0d3"; }
	static std::string google_plus_square() { return "\uf0d4"; }
	static std::string google_plus() { return "\uf0d5"; }
	static std::string money() { return "\uf0d6"; }
	static std::string caret_down() { return "\uf0d7"; }
	static std::string caret_up() { return "\uf0d8"; }
	static std::string caret_left() { return "\uf0d9"; }
	static std::string caret_right() { return "\uf0da"; }
	static std::string columns() { return "\uf0db"; }
	static std::string unsorted() { return "\uf0dc"; }
	static std::string sort() { return "\uf0dc"; }
	static std::string sort_down() { return "\uf0dd"; }
	static std::string sort_desc() { return "\uf0dd"; }
	static std::string sort_up() { return "\uf0de"; }
	static std::string sort_asc() { return "\uf0de"; }
	static std::string envelope() { return "\uf0e0"; }
	static std::string linkedin() { return "\uf0e1"; }
	static std::string rotate_left() { return "\uf0e2"; }
	static std::string undo() { return "\uf0e2"; }
	static std::string legal() { return "\uf0e3"; }
	static std::string gavel() { return "\uf0e3"; }
	static std::string dashboard() { return "\uf0e4"; }
	static std::string tachometer() { return "\uf0e4"; }
	static std::string comment_o() { return "\uf0e5"; }
	static std::string comments_o() { return "\uf0e6"; }
	static std::string flash() { return "\uf0e7"; }
	static std::string bolt() { return "\uf0e7"; }
	static std::string sitemap() { return "\uf0e8"; }
	static std::string umbrella() { return "\uf0e9"; }
	static std::string paste() { return "\uf0ea"; }
	static std::string clipboard() { return "\uf0ea"; }
	static std::string lightbulb_o() { return "\uf0eb"; }
	static std::string exchange() { return "\uf0ec"; }
	static std::string cloud_download() { return "\uf0ed"; }
	static std::string cloud_upload() { return "\uf0ee"; }
	static std::string user_md() { return "\uf0f0"; }
	static std::string stethoscope() { return "\uf0f1"; }
	static std::string suitcase() { return "\uf0f2"; }
	static std::string bell_o() { return "\uf0a2"; }
	static std::string coffee() { return "\uf0f4"; }
	static std::string cutlery() { return "\uf0f5"; }
	static std::string file_text_o() { return "\uf0f6"; }
	static std::string building_o() { return "\uf0f7"; }
	static std::string hospital_o() { return "\uf0f8"; }
	static std::string ambulance() { return "\uf0f9"; }
	static std::string medkit() { return "\uf0fa"; }
	static std::string fighter_jet() { return "\uf0fb"; }
	static std::string beer() { return "\uf0fc"; }
	static std::string h_square() { return "\uf0fd"; }
	static std::string plus_square() { return "\uf0fe"; }
	static std::string angle_double_left() { return "\uf100"; }
	static std::string angle_double_right() { return "\uf101"; }
	static std::string angle_double_up() { return "\uf102"; }
	static std::string angle_double_down() { return "\uf103"; }
	static std::string angle_left() { return "\uf104"; }
	static std::string angle_right() { return "\uf105"; }
	static std::string angle_up() { return "\uf106"; }
	static std::string angle_down() { return "\uf107"; }
	static std::string desktop() { return "\uf108"; }
	static std::string laptop() { return "\uf109"; }
	static std::string tablet() { return "\uf10a"; }
	static std::string mobile_phone() { return "\uf10b"; }
	static std::string mobile() { return "\uf10b"; }
	static std::string circle_o() { return "\uf10c"; }
	static std::string quote_left() { return "\uf10d"; }
	static std::string quote_right() { return "\uf10e"; }
	static std::string spinner() { return "\uf110"; }
	static std::string circle() { return "\uf111"; }
	static std::string mail_reply() { return "\uf112"; }
	static std::string reply() { return "\uf112"; }
	static std::string github_alt() { return "\uf113"; }
	static std::string folder_o() { return "\uf114"; }
	static std::string folder_open_o() { return "\uf115"; }
	static std::string smile_o() { return "\uf118"; }
	static std::string frown_o() { return "\uf119"; }
	static std::string meh_o() { return "\uf11a"; }
	static std::string gamepad() { return "\uf11b"; }
	static std::string keyboard_o() { return "\uf11c"; }
	static std::string flag_o() { return "\uf11d"; }
	static std::string flag_checkered() { return "\uf11e"; }
	static std::string terminal() { return "\uf120"; }
	static std::string code() { return "\uf121"; }
	static std::string mail_reply_all() { return "\uf122"; }
	static std::string reply_all() { return "\uf122"; }
	static std::string star_half_empty() { return "\uf123"; }
	static std::string star_half_full() { return "\uf123"; }
	static std::string star_half_o() { return "\uf123"; }
	static std::string location_arrow() { return "\uf124"; }
	static std::string crop() { return "\uf125"; }
	static std::string code_fork() { return "\uf126"; }
	static std::string unlink() { return "\uf127"; }
	static std::string chain_broken() { return "\uf127"; }
	static std::string question() { return "\uf128"; }
	static std::string info() { return "\uf129"; }
	static std::string exclamation() { return "\uf12a"; }
	static std::string superscript() { return "\uf12b"; }
	static std::string subscript() { return "\uf12c"; }
	static std::string eraser() { return "\uf12d"; }
	static std::string puzzle_piece() { return "\uf12e"; }
	static std::string microphone() { return "\uf130"; }
	static std::string microphone_slash() { return "\uf131"; }
	static std::string shield() { return "\uf132"; }
	static std::string calendar_o() { return "\uf133"; }
	static std::string fire_extinguisher() { return "\uf134"; }
	static std::string rocket() { return "\uf135"; }
	static std::string maxcdn() { return "\uf136"; }
	static std::string chevron_circle_left() { return "\uf137"; }
	static std::string chevron_circle_right() { return "\uf138"; }
	static std::string chevron_circle_up() { return "\uf139"; }
	static std::string chevron_circle_down() { return "\uf13a"; }
	static std::string html5() { return "\uf13b"; }
	static std::string css3() { return "\uf13c"; }
	static std::string anchor() { return "\uf13d"; }
	static std::string unlock_alt() { return "\uf13e"; }
	static std::string bullseye() { return "\uf140"; }
	static std::string ellipsis_h() { return "\uf141"; }
	static std::string ellipsis_v() { return "\uf142"; }
	static std::string rss_square() { return "\uf143"; }
	static std::string play_circle() { return "\uf144"; }
	static std::string ticket() { return "\uf145"; }
	static std::string minus_square() { return "\uf146"; }
	static std::string minus_square_o() { return "\uf147"; }
	static std::string level_up() { return "\uf148"; }
	static std::string level_down() { return "\uf149"; }
	static std::string check_square() { return "\uf14a"; }
	static std::string pencil_square() { return "\uf14b"; }
	static std::string external_link_square() { return "\uf14c"; }
	static std::string share_square() { return "\uf14d"; }
	static std::string compass() { return "\uf14e"; }
	static std::string toggle_down() { return "\uf150"; }
	static std::string caret_square_o_down() { return "\uf150"; }
	static std::string toggle_up() { return "\uf151"; }
	static std::string caret_square_o_up() { return "\uf151"; }
	static std::string toggle_right() { return "\uf152"; }
	static std::string caret_square_o_right() { return "\uf152"; }
	static std::string euro() { return "\uf153"; }
	static std::string eur() { return "\uf153"; }
	static std::string gbp() { return "\uf154"; }
	static std::string dollar() { return "\uf155"; }
	static std::string usd() { return "\uf155"; }
	static std::string rupee() { return "\uf156"; }
	static std::string inr() { return "\uf156"; }
	static std::string cny() { return "\uf157"; }
	static std::string rmb() { return "\uf157"; }
	static std::string yen() { return "\uf157"; }
	static std::string jpy() { return "\uf157"; }
	static std::string ruble() { return "\uf158"; }
	static std::string rouble() { return "\uf158"; }
	static std::string rub() { return "\uf158"; }
	static std::string won() { return "\uf159"; }
	static std::string krw() { return "\uf159"; }
	static std::string bitcoin() { return "\uf15a"; }
	static std::string btc() { return "\uf15a"; }
	static std::string file() { return "\uf15b"; }
	static std::string file_text() { return "\uf15c"; }
	static std::string sort_alpha_asc() { return "\uf15d"; }
	static std::string sort_alpha_desc() { return "\uf15e"; }
	static std::string sort_amount_asc() { return "\uf160"; }
	static std::string sort_amount_desc() { return "\uf161"; }
	static std::string sort_numeric_asc() { return "\uf162"; }
	static std::string sort_numeric_desc() { return "\uf163"; }
	static std::string thumbs_up() { return "\uf164"; }
	static std::string thumbs_down() { return "\uf165"; }
	static std::string youtube_square() { return "\uf166"; }
	static std::string youtube() { return "\uf167"; }
	static std::string xing() { return "\uf168"; }
	static std::string xing_square() { return "\uf169"; }
	static std::string youtube_play() { return "\uf16a"; }
	static std::string dropbox() { return "\uf16b"; }
	static std::string stack_overflow() { return "\uf16c"; }
	static std::string instagram() { return "\uf16d"; }
	static std::string flickr() { return "\uf16e"; }
	static std::string adn() { return "\uf170"; }
	static std::string bitbucket() { return "\uf171"; }
	static std::string bitbucket_square() { return "\uf172"; }
	static std::string tumblr() { return "\uf173"; }
	static std::string tumblr_square() { return "\uf174"; }
	static std::string long_arrow_down() { return "\uf175"; }
	static std::string long_arrow_up() { return "\uf176"; }
	static std::string long_arrow_left() { return "\uf177"; }
	static std::string long_arrow_right() { return "\uf178"; }
	static std::string apple() { return "\uf179"; }
	static std::string windows() { return "\uf17a"; }
	static std::string android() { return "\uf17b"; }
	static std::string linux() { return "\uf17c"; }
	static std::string dribbble() { return "\uf17d"; }
	static std::string skype() { return "\uf17e"; }
	static std::string foursquare() { return "\uf180"; }
	static std::string trello() { return "\uf181"; }
	static std::string female() { return "\uf182"; }
	static std::string male() { return "\uf183"; }
	static std::string gittip() { return "\uf184"; }
	static std::string sun_o() { return "\uf185"; }
	static std::string moon_o() { return "\uf186"; }
	static std::string archive() { return "\uf187"; }
	static std::string bug() { return "\uf188"; }
	static std::string vk() { return "\uf189"; }
	static std::string weibo() { return "\uf18a"; }
	static std::string renren() { return "\uf18b"; }
	static std::string pagelines() { return "\uf18c"; }
	static std::string stack_exchange() { return "\uf18d"; }
	static std::string arrow_circle_o_right() { return "\uf18e"; }
	static std::string arrow_circle_o_left() { return "\uf190"; }
	static std::string toggle_left() { return "\uf191"; }
	static std::string caret_square_o_left() { return "\uf191"; }
	static std::string dot_circle_o() { return "\uf192"; }
	static std::string wheelchair() { return "\uf193"; }
	static std::string vimeo_square() { return "\uf194"; }
	static std::string turkish_lira() { return "\uf195"; }
	static std::string plus_square_o() { return "\uf196"; }
	static std::string space_shuttle() { return "\uf197"; }
	static std::string slack() { return "\uf198"; }
	static std::string envelope_square() { return "\uf199"; }
	static std::string wordpress() { return "\uf19a"; }
	static std::string openid() { return "\uf19b"; }
	static std::string institution() { return "\uf19c"; }
	static std::string bank() { return "\uf19c"; }
	static std::string university() { return "\uf19c"; }
	static std::string mortar_board() { return "\uf19d"; }
	static std::string graduation_cap() { return "\uf19d"; }
	static std::string yahoo() { return "\uf19e"; }
	static std::string google() { return "\uf1a0"; }
	static std::string reddit() { return "\uf1a1"; }
	static std::string reddit_square() { return "\uf1a2"; }
	static std::string stumbleupon_circle() { return "\uf1a3"; }
	static std::string stumbleupon() { return "\uf1a4"; }
	static std::string delicious() { return "\uf1a5"; }
	static std::string digg() { return "\uf1a6"; }
	static std::string pied_piper() { return "\uf1a7"; }
	static std::string pied_piper_alt() { return "\uf1a8"; }
	static std::string drupal() { return "\uf1a9"; }
	static std::string joomla() { return "\uf1aa"; }
	static std::string language() { return "\uf1ab"; }
	static std::string fax() { return "\uf1ac"; }
	static std::string building() { return "\uf1ad"; }
	static std::string child() { return "\uf1ae"; }
	static std::string paw() { return "\uf1b0"; }
	static std::string spoon() { return "\uf1b1"; }
	static std::string cube() { return "\uf1b2"; }
	static std::string cubes() { return "\uf1b3"; }
	static std::string behance() { return "\uf1b4"; }
	static std::string behance_square() { return "\uf1b5"; }
	static std::string steam() { return "\uf1b6"; }
	static std::string steam_square() { return "\uf1b7"; }
	static std::string recycle() { return "\uf1b8"; }
	static std::string automobile() { return "\uf1b9"; }
	static std::string car() { return "\uf1b9"; }
	static std::string cab() { return "\uf1ba"; }
	static std::string taxi() { return "\uf1ba"; }
	static std::string tree() { return "\uf1bb"; }
	static std::string spotify() { return "\uf1bc"; }
	static std::string deviantart() { return "\uf1bd"; }
	static std::string soundcloud() { return "\uf1be"; }
	static std::string database() { return "\uf1c0"; }
	static std::string file_pdf_o() { return "\uf1c1"; }
	static std::string file_word_o() { return "\uf1c2"; }
	static std::string file_excel_o() { return "\uf1c3"; }
	static std::string file_powerpoint_o() { return "\uf1c4"; }
	static std::string file_photo_o() { return "\uf1c5"; }
	static std::string file_picture_o() { return "\uf1c5"; }
	static std::string file_image_o() { return "\uf1c5"; }
	static std::string file_zip_o() { return "\uf1c6"; }
	static std::string file_archive_o() { return "\uf1c6"; }
	static std::string file_sound_o() { return "\uf1c7"; }
	static std::string file_audio_o() { return "\uf1c7"; }
	static std::string file_movie_o() { return "\uf1c8"; }
	static std::string file_video_o() { return "\uf1c8"; }
	static std::string file_code_o() { return "\uf1c9"; }
	static std::string vine() { return "\uf1ca"; }
	static std::string codepen() { return "\uf1cb"; }
	static std::string jsfiddle() { return "\uf1cc"; }
	static std::string life_bouy() { return "\uf1cd"; }
	static std::string life_buoy() { return "\uf1cd"; }
	static std::string life_saver() { return "\uf1cd"; }
	static std::string support() { return "\uf1cd"; }
	static std::string life_ring() { return "\uf1cd"; }
	static std::string circle_o_notch() { return "\uf1ce"; }
	static std::string ra() { return "\uf1d0"; }
	static std::string rebel() { return "\uf1d0"; }
	static std::string ge() { return "\uf1d1"; }
	static std::string empire() { return "\uf1d1"; }
	static std::string git_square() { return "\uf1d2"; }
	static std::string git() { return "\uf1d3"; }
	static std::string hacker_news() { return "\uf1d4"; }
	static std::string tencent_weibo() { return "\uf1d5"; }
	static std::string qq() { return "\uf1d6"; }
	static std::string wechat() { return "\uf1d7"; }
	static std::string weixin() { return "\uf1d7"; }
	static std::string send() { return "\uf1d8"; }
	static std::string paper_plane() { return "\uf1d8"; }
	static std::string send_o() { return "\uf1d9"; }
	static std::string paper_plane_o() { return "\uf1d9"; }
	static std::string history() { return "\uf1da"; }
	static std::string circle_thin() { return "\uf1db"; }
	static std::string header() { return "\uf1dc"; }
	static std::string paragraph() { return "\uf1dd"; }
	static std::string sliders() { return "\uf1de"; }
	static std::string share_alt() { return "\uf1e0"; }
	static std::string share_alt_square() { return "\uf1e1"; }
	static std::string bomb() { return "\uf1e2"; }
	static std::string soccer_ball_o() { return "\uf1e3"; }
	static std::string futbol_o() { return "\uf1e3"; }
	static std::string tty() { return "\uf1e4"; }
	static std::string binoculars() { return "\uf1e5"; }
	static std::string plug() { return "\uf1e6"; }
	static std::string slideshare() { return "\uf1e7"; }
	static std::string twitch() { return "\uf1e8"; }
	static std::string yelp() { return "\uf1e9"; }
	static std::string newspaper_o() { return "\uf1ea"; }
	static std::string wifi() { return "\uf1eb"; }
	static std::string calculator() { return "\uf1ec"; }
	static std::string paypal() { return "\uf1ed"; }
	static std::string google_wallet() { return "\uf1ee"; }
	static std::string cc_visa() { return "\uf1f0"; }
	static std::string cc_mastercard() { return "\uf1f1"; }
	static std::string cc_discover() { return "\uf1f2"; }
	static std::string cc_amex() { return "\uf1f3"; }
	static std::string cc_paypal() { return "\uf1f4"; }
	static std::string cc_stripe() { return "\uf1f5"; }
	static std::string bell_slash() { return "\uf1f6"; }
	static std::string bell_slash_o() { return "\uf1f7"; }
	static std::string trash() { return "\uf1f8"; }
	static std::string copyright() { return "\uf1f9"; }
	static std::string at() { return "\uf1fa"; }
	static std::string eyedropper() { return "\uf1fb"; }
	static std::string paint_brush() { return "\uf1fc"; }
	static std::string birthday_cake() { return "\uf1fd"; }
	static std::string area_chart() { return "\uf1fe"; }
	static std::string pie_chart() { return "\uf200"; }
	static std::string line_chart() { return "\uf201"; }
	static std::string lastfm() { return "\uf202"; }
	static std::string lastfm_square() { return "\uf203"; }
	static std::string toggle_off() { return "\uf204"; }
	static std::string toggle_on() { return "\uf205"; }
	static std::string bicycle() { return "\uf206"; }
	static std::string bus() { return "\uf207"; }
	static std::string ioxhost() { return "\uf208"; }
	static std::string angellist() { return "\uf209"; }
	static std::string cc() { return "\uf20a"; }
	static std::string shekel() { return "\uf20b"; }
	static std::string sheqel() { return "\uf20b"; }
	static std::string ils() { return "\uf20b"; }
	static std::string meanpath() { return "\uf20c"; }
	static std::string allChars() { return "\uf000\uf001\uf002\uf003\uf004\uf005\uf006\uf007\uf008\uf009\uf00a\uf00b\uf00c\uf00d\uf00e\uf010\uf011\uf012\uf013\uf014\uf015\uf016\uf017\uf018\uf019\uf01a\uf01b\uf01c\uf01d\uf01e\uf021\uf022\uf023\uf024\uf025\uf026\uf027\uf028\uf029\uf02a\uf02b\uf02c\uf02d\uf02e\uf02f\uf030\uf031\uf032\uf033\uf034\uf035\uf036\uf037\uf038\uf039\uf03a\uf03b\uf03c\uf03d\uf03e\uf040\uf041\uf042\uf043\uf044\uf045\uf046\uf047\uf048\uf049\uf04a\uf04b\uf04c\uf04d\uf04e\uf050\uf051\uf052\uf053\uf054\uf055\uf056\uf057\uf058\uf059\uf05a\uf05b\uf05c\uf05d\uf05e\uf060\uf061\uf062\uf063\uf064\uf065\uf066\uf067\uf068\uf069\uf06a\uf06b\uf06c\uf06d\uf06e\uf070\uf071\uf072\uf073\uf074\uf075\uf076\uf077\uf078\uf079\uf07a\uf07b\uf07c\uf07d\uf07e\uf080\uf081\uf082\uf083\uf084\uf085\uf086\uf087\uf088\uf089\uf08a\uf08b\uf08c\uf08d\uf08e\uf090\uf091\uf092\uf093\uf094\uf095\uf096\uf097\uf098\uf099\uf09a\uf09b\uf09c\uf09d\uf09e\uf0a0\uf0a1\uf0f3\uf0a3\uf0a4\uf0a5\uf0a6\uf0a7\uf0a8\uf0a9\uf0aa\uf0ab\uf0ac\uf0ad\uf0ae\uf0b0\uf0b1\uf0b2\uf0c0\uf0c1\uf0c2\uf0c3\uf0c4\uf0c5\uf0c6\uf0c7\uf0c8\uf0c9\uf0ca\uf0cb\uf0cc\uf0cd\uf0ce\uf0d0\uf0d1\uf0d2\uf0d3\uf0d4\uf0d5\uf0d6\uf0d7\uf0d8\uf0d9\uf0da\uf0db\uf0dc\uf0dd\uf0de\uf0e0\uf0e1\uf0e2\uf0e3\uf0e4\uf0e5\uf0e6\uf0e7\uf0e8\uf0e9\uf0ea\uf0eb\uf0ec\uf0ed\uf0ee\uf0f0\uf0f1\uf0f2\uf0a2\uf0f4\uf0f5\uf0f6\uf0f7\uf0f8\uf0f9\uf0fa\uf0fb\uf0fc\uf0fd\uf0fe\uf100\uf101\uf102\uf103\uf104\uf105\uf106\uf107\uf108\uf109\uf10a\uf10b\uf10c\uf10d\uf10e\uf110\uf111\uf112\uf113\uf114\uf115\uf118\uf119\uf11a\uf11b\uf11c\uf11d\uf11e\uf120\uf121\uf122\uf123\uf124\uf125\uf126\uf127\uf128\uf129\uf12a\uf12b\uf12c\uf12d\uf12e\uf130\uf131\uf132\uf133\uf134\uf135\uf136\uf137\uf138\uf139\uf13a\uf13b\uf13c\uf13d\uf13e\uf140\uf141\uf142\uf143\uf144\uf145\uf146\uf147\uf148\uf149\uf14a\uf14b\uf14c\uf14d\uf14e\uf150\uf151\uf152\uf153\uf154\uf155\uf156\uf157\uf158\uf159\uf15a\uf15b\uf15c\uf15d\uf15e\uf160\uf161\uf162\uf163\uf164\uf165\uf166\uf167\uf168\uf169\uf16a\uf16b\uf16c\uf16d\uf16e\uf170\uf171\uf172\uf173\uf174\uf175\uf176\uf177\uf178\uf179\uf17a\uf17b\uf17c\uf17d\uf17e\uf180\uf181\uf182\uf183\uf184\uf185\uf186\uf187\uf188\uf189\uf18a\uf18b\uf18c\uf18d\uf18e\uf190\uf191\uf192\uf193\uf194\uf195\uf196\uf197\uf198\uf199\uf19a\uf19b\uf19c\uf19d\uf19e\uf1a0\uf1a1\uf1a2\uf1a3\uf1a4\uf1a5\uf1a6\uf1a7\uf1a8\uf1a9\uf1aa\uf1ab\uf1ac\uf1ad\uf1ae\uf1b0\uf1b1\uf1b2\uf1b3\uf1b4\uf1b5\uf1b6\uf1b7\uf1b8\uf1b9\uf1ba\uf1bb\uf1bc\uf1bd\uf1be\uf1c0\uf1c1\uf1c2\uf1c3\uf1c4\uf1c5\uf1c6\uf1c7\uf1c8\uf1c9\uf1ca\uf1cb\uf1cc\uf1cd\uf1ce\uf1d0\uf1d1\uf1d2\uf1d3\uf1d4\uf1d5\uf1d6\uf1d7\uf1d8\uf1d9\uf1da\uf1db\uf1dc\uf1dd\uf1de\uf1e0\uf1e1\uf1e2\uf1e3\uf1e4\uf1e5\uf1e6\uf1e7\uf1e8\uf1e9\uf1ea\uf1eb\uf1ec\uf1ed\uf1ee\uf1f0\uf1f1\uf1f2\uf1f3\uf1f4\uf1f5\uf1f6\uf1f7\uf1f8\uf1f9\uf1fa\uf1fb\uf1fc\uf1fd\uf1fe\uf200\uf201\uf202\uf203\uf204\uf205\uf206\uf207\uf208\uf209\uf20a\uf20b\uf20c"; }
	static std::pair<uint16_t,uint16_t> charsRange() { return { 0xf000, 0xf20c }; }

};