#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FAST_READ 1
#define READ_TO_BUFFER 0
#define USE_VOXELS_COMPUTE_SHADER 0
#define USE_PARTICLES_COMPUTE_SHADER 1
#define MAX_PARTICLE_SIZE 5

#endif // CONSTANTS_H
