#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FAST_READ 1
#define READ_TO_BUFFER 0

#define USE_RAW 0
#define USE_VOXELS_COMPUTE_SHADER 0
#define USE_PARTICLES_COMPUTE_SHADER 1
#define USE_PARTICLES_HISTOGRAM 1
#define USE_VOXELS_DCT_COMPRESSION 0
#define USE_VBO 0
#define USE_HALF_PARTICLE 1

#define MAX_PARTICLE_SIZE 5
#define USE_TEXTURE_3D_MIPMAPS 1

#endif // CONSTANTS_H
